### PR TITLE
Fix array out of bounds in hpack

### PR DESCRIPTION
**Pull request by jonathanjameswatson**
This PR stops the server from hanging when a response has a non-empty www-authenticate header.

PS: I was not able to easily run ocamlformat for this PR, so you may need to run it.

### CODE REVIEW

**Comment by anmonteiro** [comment]
Thank you! Could you provide more information as to how you came across this bug?

Ideally we would be able to craft a test that exposes the problem so that we don't regress in the future.

**Comment by anmonteiro** [comment]
> PS: I was not able to easily run ocamlformat for this PR, so you may need to run it.

I just pushed a commit fixing this.

**Comment by jonathanjameswatson** [comment]
> Thank you! Could you provide more information as to how you came across this bug?
> 
> Ideally we would be able to craft a test that exposes the problem so that we don't regress in the future.

I came across this bug in a test that was trying to send a response with the www-authenticate header. I've added a test to my PR for this.

**Comment by anmonteiro** [comment]
Thanks for adding a test! I checked out the PR locally, and the fix makes sense.

I made a small modification to your patch that avoids allocating an option type when the static table entry is found.

**Comment by jonathanjameswatson** [comment]
Thank you!

**Comment by anmonteiro** [comment]
Thanks again!

**Pull request merged**
